language: node_js
node_js:
  - 8
  - 10
  - 11

notifications:
  email: false

jobs:
  include:
    - stage: test
      before_install:
        - npm install -g codecov greenkeeper-lockfile
      before_script: greenkeeper-lockfile-update
      script:
        - npm run test
        - codecov
      after_script: greenkeeper-lockfile-upload
    - stage: deploy
      if: branch == master && !fork
      node_js: node # pre-installed version
      script:
        - npm install -g semantic-release
        - semantic-release
